steps:
 #build the container image
- name: 'docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops', ''.'']
  # push container image
images:
- 'gcr.io/$PROJECT_ID/gcpdevops'
# - name: "gcr.io/cloud-builders/docker"
#  args: ["push", "gcr.io/$PROJECT_ID/gcpdevops"]
  # deploy container image to GKE
# - name: "gcr.io/cloud-builders/gke-deploy"
#  args:
#  - run
#  - --filename=gke.yaml
#  - --image=gcr.io/$PROJECT_ID/gcpdevops
#  - --location=us-central1-c
#  - --cluster=gcp-devops-cluster
#  - --namespace=gcp-devops-prod